### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by PolGuixe** [babel/generator-babel-boilerplate#382] opened 2016-07-18 10:15 UTC
I am getting this error in Chrome console with a package I made with this boilerplate: `Failed to parse SourceMap`.

But the map is under the `/dist` folder.

**Comment by jmeas** [comment] 2016-07-18 15:39
Is the repo open source? If so, can you post a link to it?

Did you make any changes to the Gulpfile? What version of the boilerplate are you using?

Provide as much info as you can and I'd be happy to help out :)

**Comment by paulfalgout** [comment] 2016-07-18 19:20
Any chance this is related to: https://github.com/webpack/webpack/issues/2145

**Comment by jmeas** [comment] 2016-07-18 19:30
Good find, @paulfalgout. Definitely seems like it could be related.

**Comment by PolGuixe** [comment] 2016-07-18 21:43
@jmeas the repo is this one: 
https://github.com/Zetoff/zetoff-three

**Comment by PolGuixe** [comment] 2016-07-18 22:04
@paulfalgout, @jmeas yes I am using Chrome and the issue is probably related to it. I don't see the same error in Safari.

And I am using Meteor as a build tool. 

Is any of you experiencing a similar issue?

**Comment by jmeas** [comment] 2016-07-18 23:15
Thanks for the update, @PolGuixe ! I'll check out the project later.

> Is any of you experiencing a similar issue?

Tbqh I started a new job and haven't used the modules I've made (which are mostly for projects at my old job), so it's been some time since I've been consuming libs built by this boilerplate. I have a few ideas in mind for modules that I plan to build and start using soon, but I haven't yet done it.

So to answer your question, nope : [

**Comment by jmeas** [comment] 2016-07-29 16:48
For future visitors, refer to the issue that @paulfalgout posted above. It seems that switching the source map option from eval to other options has helped some people.

I'll likely look into this soon to switch the boilerplate off of eval to one that works for me and some other test machines.

**Comment by jmeas** [comment] 2017-07-06 01:29
Alright, I'm going to close this due to this recent comment: https://github.com/webpack/webpack/issues/2145#issuecomment-312400334

If anyone has further issues with this, refer to:

- the above comments, which suggest some fixes
- the linked webpack issue, which dives more into the root of the problem (it's a long issue...be warned)

If you think the issue is caused by this boilerplate specifically, leave a comment here and we can continue the discussion.

**Closed by jmeas** 2017-07-06 01:29 UTC
Labels: bug, upstream
