### ISSUE TITLE
Export "ordinary" browser library, without `default` property

### ISSUE THREAD

**Issue by alinnert** [babel/generator-babel-boilerplate#362] opened 2016-06-15 13:55 UTC
Is there a way to build my project so I can use it like other ordinary libraries (like jQuery, moment.js etc.).

When I build my project and I load the file in the dist folder in an html file via a `<script src="myLib.js">` element I get an object containing a `default` property. E. g. `myLib.default.initMyLib()`.

What I want instead is an object like this: `myLib.initMyLib()`. Is this possible using this boilerplate? If so, how?

**Comment by jmeas** [comment] 2016-06-15 15:29
It used to work that way, and should still. I just haven't loaded a library like that in a long time, so a regression may have been introduced. I'll look into it and try to get this fixed up 🙂

**Comment by jmeas** [comment] 2016-06-17 05:15
@alinnert , I dug into it. This is caused by Babel v6 + Webpack v1's current behavior.

Webpack v2 should handle it as you'd expect, but it's in beta so I don't plan to update the boilerplate to use it atm. A PR to update the behavior in Webpack v1 is open over here:

https://github.com/webpack/core/pull/23

Related issue: https://github.com/webpack/webpack/issues/2047

Not too much I can do in the meantime!

//cc @marcandre this one's going to matter to you, if I had to guess 😛

**Comment by jmeas** [comment] 2016-06-29 22:54
Cross-referencing #368 which is relevant

**Comment by jmeas** [comment] 2016-07-19 18:46
I can fix this with [this plugin](https://github.com/59naga/babel-plugin-add-module-exports). I'll add this very soon.

**Comment by jmeas** [comment] 2016-08-25 04:46
@alinnert the fix for this is straightforward to implement in a per-project basis by adding [this plugin](https://github.com/59naga/babel-plugin-add-module-exports). For this reason, I'm going to hold off on adding it to the boilerplate for the time being.

**Comment by jmeas** [comment] 2016-08-26 06:51
I'm going to reopen this to remind myself to add a section to either the FAQ or the trouble shooting section for this.

**Comment by gabrielstuff** [comment] 2016-09-20 22:01
The plugin works great ! Thanks. Indeed, adding to the FAQ / README, would be nice.

**Comment by jmeas** [comment] 2016-09-20 23:04
@gabrielstuff would you have time to add it to the README? :) I'd happily merge it in!

**Comment by gabrielstuff** [comment] 2016-09-20 23:06
Tomorrow morning, with pleasure. Struggling a bit with my externals and other webpack funs. Thanks

**Comment by jmeas** [comment] 2016-09-20 23:34
Awesome. Thanks so much @gabrielstuff !

**Closed** 2016-09-21 22:16 UTC
Labels: documentation, revisit
